/**
 * WebhookServer — a generic, secret-gated inbound HTTP API that turns an external
 * POST into hive work and lets the caller poll that work's status by a token.
 *
 * Modeled on `SlackWebhookServer` (same zero-SDK `node:http` + `tunnelmole`
 * approach) but for arbitrary callers rather than Slack's Events API:
 *   - POST <endpoint>  + `x-md-webhook-secret: <secret>` + JSON `{ message, title? }`
 *       → routes the message to god/Michael, creates a stamped kanban card, and
 *         returns a freshly-minted capability TOKEN: `{ ok, token, taskId }`.
 *   - GET  <endpoint>  + `x-md-webhook-token: <token>` (or `?token=`)
 *       → returns ONLY that token's task status: `{ ok, status, title, result? }`.
 *
 * SECURITY — this is a PUBLIC surface (tunnel-forwarded), unlike the loopback
 * /reply endpoint, so the gate is strict:
 *   - constant-time secret comparison (`timingSafeEqual`, length-guarded),
 *   - the secret is read from options and NEVER logged, echoed, or forwarded into
 *     the routed message / card / response,
 *   - the capability token is unguessable (generated by the caller-side handler,
 *     192-bit) and a GET reveals only the single task it maps to — no listing or
 *     enumeration of other work,
 *   - a request body cap + a basic fixed-window rate limit bound abuse before any
 *     parsing or crypto runs.
 *
 * Runs in the Electron main process. Deliberately free of any `electron` import so
 * it can be unit-/smoke-tested as a plain Node module. The actual card creation +
 * god routing + token→status lookup are injected as callbacks (they need hive
 * access, which lives in the main entrypoint); this class owns only transport,
 * the secret gate, rate limiting, and the tunnel.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { timingSafeEqual } from 'node:crypto';
// `tunnelmole` is an ESM-only package; the Electron main process is bundled as
// CommonJS, so a static import becomes a `require()` of ESM and throws
// ERR_REQUIRE_ESM at load. Load it via dynamic import() at the call site (see
// openTunnel) — dynamic import can pull ESM from CJS.

/** The validated body of an accepted POST — just the work to do. The secret has
 *  already been verified and is intentionally NOT part of this shape, so it can
 *  never be forwarded onward. */
export interface WebhookInbound {
  message: string;
  title?: string;
}

/** What a GET exposes for a token — mirrors the kanban's public columns only. */
export interface WebhookTaskStatus {
  status: string;
  title: string;
  result?: string;
}

export interface WebhookServerOptions {
  /** Local TCP port the HTTP server binds to (and the tunnel forwards to). */
  port: number;
  /** Shared secret the caller must echo in `x-md-webhook-secret`. Required. */
  secret: string;
  /**
   * Turn a verified POST into hive work. MUST create the kanban card + route to
   * god and return the capability token to hand back (plus the card id). Return
   * null to signal a server-side failure (→ 500). The token it returns is the
   * ONLY thing echoed to the caller; the secret never reaches here.
   */
  onMessage: (msg: WebhookInbound) => { token: string; taskId: string } | null;
  /**
   * Resolve a capability token to its task's public status, or null when the
   * token maps to nothing (→ 404). MUST be scoped to the one token — it must
   * never reveal or enumerate any other task.
   */
  lookupStatus: (token: string) => WebhookTaskStatus | null;
}

/** Reject bodies larger than this before buffering — callers send tiny JSON; the
 *  cap stops an unauthenticated peer forcing unbounded memory use pre-auth. */
const MAX_BODY_BYTES = 1024 * 1024; // 1 MB
/** Cap how long we wait for the public tunnel before giving up (server stays up). */
const TUNNEL_START_TIMEOUT_MS = 10_000;
/** Basic abuse guard: at most this many requests per fixed window, globally. */
const RATE_LIMIT = 120;
const RATE_WINDOW_MS = 60_000;

export class WebhookServer {
  private server: Server | null = null;
  private tunnelUrl: string | null = null;
  private readonly port: number;
  private readonly secret: string;
  private readonly onMessage: (msg: WebhookInbound) => { token: string; taskId: string } | null;
  private readonly lookupStatus: (token: string) => WebhookTaskStatus | null;
  // Fixed-window rate limiter (global; the remote IP is the tunnel's, so per-IP
  // would be meaningless behind tunnelmole).
  private windowStart = 0;
  private windowCount = 0;

  constructor(opts: WebhookServerOptions) {
    this.port = opts.port;
    this.secret = opts.secret;
    this.onMessage = opts.onMessage;
    this.lookupStatus = opts.lookupStatus;
  }

  /**
   * Bind the local HTTP server, then open a public tunnel to it. The HTTP handler
   * (the security boundary) is live the instant `listen` resolves; the tunnel is
   * opened afterwards and is non-fatal — if it can't be established the server
   * keeps running and we report the tunnel error without a URL.
   */
  async start(): Promise<{ ok: boolean; url?: string; error?: string }> {
    if (this.server) return { ok: false, error: 'already running' };
    if (!this.secret) return { ok: false, error: 'missing webhook secret' };
    try {
      await this.listen();
    } catch (e) {
      this.stop();
      return { ok: false, error: `failed to bind port ${this.port}: ${errMsg(e)}` };
    }
    try {
      const url = await this.openTunnel();
      if (!url) throw new Error('tunnelmole returned empty URL');
      this.tunnelUrl = url;
      // tunnelmole runs in the background; there is no close handle to wire here.
      return { ok: true, url };
    } catch (e) {
      // Surface the tunnel failure rather than silently returning ok:true with no url.
      return { ok: false, error: `tunnel unavailable: ${errMsg(e)}` };
    }
  }

  /** Close the HTTP server. Idempotent and best-effort.
   *  Note: tunnelmole has no documented close handle; teardown is best-effort. */
  stop(): void {
    this.tunnelUrl = null;
    try { this.server?.close(); } catch { /* noop */ }
    this.server = null;
  }

  private listen(): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      const server = createServer((req, res) => this.handleRequest(req, res));
      const onError = (e: Error): void => reject(e);
      server.once('error', onError);
      server.listen(this.port, () => {
        server.off('error', onError);
        this.server = server;
        resolve();
      });
    });
  }

  private openTunnel(): Promise<string> {
    // TODO: optional persistent domain — pass `domain` here when config carries one.
    return new Promise<string>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('timed out')), TUNNEL_START_TIMEOUT_MS);
      import('tunnelmole')
        .then(({ tunnelmole }) => tunnelmole({ port: this.port }))
        .then((url) => { clearTimeout(timer); resolve(url); })
        .catch((e) => { clearTimeout(timer); reject(e); });
    });
  }

  /** Fixed-window limiter — bounds total work before any parse/crypto runs. */
  private allowRequest(): boolean {
    const now = Date.now();
    if (now - this.windowStart > RATE_WINDOW_MS) { this.windowStart = now; this.windowCount = 0; }
    this.windowCount += 1;
    return this.windowCount <= RATE_LIMIT;
  }

  private handleRequest(req: IncomingMessage, res: ServerResponse): void {
    // Rate limit first — cheapest possible rejection, ahead of any work.
    if (!this.allowRequest()) { json(res, 429, { ok: false, error: 'rate limited' }); return; }
    const method = req.method ?? '';
    if (method === 'GET') { this.handleStatus(req, res); return; }
    if (method === 'POST') { this.handleCreate(req, res); return; }
    res.writeHead(405); res.end();
  }

  /** GET — return the status of the token's task (token only; never a listing). */
  private handleStatus(req: IncomingMessage, res: ServerResponse): void {
    const token = readToken(req);
    if (!token) { json(res, 401, { ok: false, error: 'token required' }); return; }
    let status: WebhookTaskStatus | null = null;
    try { status = this.lookupStatus(token); }
    catch { json(res, 500, { ok: false, error: 'lookup failed' }); return; }
    // 404 for an unknown token — identical to a malformed one, so a probe can't
    // distinguish "valid but unknown" from "wrong shape" (no enumeration signal).
    if (!status) { json(res, 404, { ok: false, error: 'not found' }); return; }
    json(res, 200, { ok: true, status: status.status, title: status.title, result: status.result ?? null });
  }

  /** POST — verify the secret, then buffer + dispatch the JSON body. */
  private handleCreate(req: IncomingMessage, res: ServerResponse): void {
    // Authenticate BEFORE reading the body so an unauthenticated peer can't even
    // make us buffer (within the size cap). 401 on any failure — no detail leaked.
    if (!this.verifySecret(req)) { json(res, 401, { ok: false, error: 'unauthorized' }); return; }

    const chunks: Buffer[] = [];
    let size = 0;
    let aborted = false;
    req.on('data', (c: Buffer) => {
      if (aborted) return;
      size += c.length;
      if (size > MAX_BODY_BYTES) { aborted = true; json(res, 413, { ok: false, error: 'too large' }); req.destroy(); return; }
      chunks.push(c);
    });
    req.on('end', () => {
      if (aborted) return;
      let parsed: { message?: unknown; title?: unknown };
      try { parsed = JSON.parse(Buffer.concat(chunks).toString('utf8')); }
      catch { json(res, 400, { ok: false, error: 'bad json' }); return; }
      const message = typeof parsed.message === 'string' ? parsed.message.trim() : '';
      if (!message) { json(res, 400, { ok: false, error: 'message required' }); return; }
      const title = typeof parsed.title === 'string' && parsed.title.trim() ? parsed.title.trim() : undefined;
      let out: { token: string; taskId: string } | null = null;
      try { out = this.onMessage({ message, title }); }
      catch { json(res, 500, { ok: false, error: 'could not create task' }); return; }
      if (!out) { json(res, 500, { ok: false, error: 'could not create task' }); return; }
      json(res, 200, { ok: true, token: out.token, taskId: out.taskId });
    });
    req.on('error', () => { if (!aborted) { try { res.writeHead(400); res.end(); } catch { /* socket gone */ } } });
  }

  /**
   * Constant-time check that `x-md-webhook-secret` equals the configured secret.
   * A length mismatch is itself a failure and short-circuits before the compare
   * (timingSafeEqual throws on unequal lengths).
   */
  private verifySecret(req: IncomingMessage): boolean {
    const provided = req.headers['x-md-webhook-secret'];
    if (typeof provided !== 'string') return false;
    const a = Buffer.from(provided);
    const b = Buffer.from(this.secret);
    if (a.length !== b.length) return false;
    return timingSafeEqual(a, b);
  }
}

/** Pull the capability token from the `x-md-webhook-token` header, falling back
 *  to a `?token=` query param. Header is preferred (kept out of URL/access logs). */
function readToken(req: IncomingMessage): string {
  const h = req.headers['x-md-webhook-token'];
  if (typeof h === 'string' && h.trim()) return h.trim();
  try {
    const url = new URL(req.url ?? '', 'http://localhost');
    const q = url.searchParams.get('token');
    if (q && q.trim()) return q.trim();
  } catch { /* malformed url → no token */ }
  return '';
}

function json(res: ServerResponse, status: number, body: unknown): void {
  try {
    res.writeHead(status, { 'content-type': 'application/json' });
    res.end(JSON.stringify(body));
  } catch { /* socket already gone */ }
}

function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}
